### ISSUE TITLE
Melee attacks count as losing ticks

### ISSUE THREAD

**Issue by jjlabont** [powerus117/RLCGPerformanceTracker#1]
![image](https://github.com/user-attachments/assets/ee439a06-5172-49ff-a2e6-b9a60b7f9ebd)

Noticed my performance with melee had a ton of lost ticks. It seems like something is wrong with tick loss counter when doing melee attacks. Easiest way to see this is to run into the boss fight with sceptre and you should start losing ticks after meleeing 
Hunleff a few times.

**Comment by jjlabont** [comment]
![image](https://github.com/user-attachments/assets/3715df9a-894b-420c-92b7-d3c58cd28c4e)

Also tested with halberd just to make sure it wasn't a sceptre thing.

**Comment by powerus117** [comment]
Thanks for reporting. The bug has been fixed in the latest version that is currently on PR (see here for status https://github.com/runelite/plugin-hub/pull/6570). In the meantime you could use the halbert on a different attack style as that should solve it for now. For the sceptre, you'd have to wait for a new update.

**Comment by powerus117** [comment]
Should be fixed in latest version, let me know if not the case.
